// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

// eager load controllers
// this doesn't work
// import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
// eagerLoadControllersFrom("components", application)
