default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tasks_tracker_app_development

test:
  <<: *default
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: <%= ENV["POSTGRES_DB"] %>

production:
  <<: *default
  database: tasks_tracker_app_production
  username: tasks_tracker_app
  password: <%= ENV["TASKS_TRACKER_APP_DATABASE_PASSWORD"] %>
